package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import clases.Conexion;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



public class grafica_dolar_vs_pesoColombiano extends javax.swing.JFrame {

    public grafica_dolar_vs_pesoColombiano() {
        initComponents();
        initComponents();
        setSize(728, 545);
        setResizable(false);
        setTitle("Dolar vs Peso Colombiano");
        setLocationRelativeTo(null);

//        ImageIcon imageIcon = new ImageIcon("src/images/LicenciaFondo.jpg");
//        Icon icono = new ImageIcon(imageIcon.getImage().getScaledInstance(jLabel_WallPaper.getWidth(),
//                jLabel_WallPaper.getHeight(), Image.SCALE_DEFAULT));
//        jLabel_WallPaper.setIcon(icono);
//        this.repaint();
        SetImageLabel(jLabel_WallPaper, "src/images/graficasFondo.jpg");
        SetImageLabel(jLabel_grafica_dolar_vs_pesoColombiano, "src/images/grafica_dolar_vs_pesoC.jpg");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_grafica_dolar_vs_pesoColombiano = new javax.swing.JLabel();
        jButton_verHistorico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_WallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_grafica_dolar_vs_pesoColombiano, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 590, 310));

        jButton_verHistorico.setText("Descargar Historico");
        jButton_verHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_verHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_verHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 160, 40));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel1.setText("Comportamiento del Dolar frente al Peso Colombiano");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 620, -1));
        getContentPane().add(jLabel_WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_verHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_verHistoricoActionPerformed

        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar archivo Excel");
        
        
        javax.swing.filechooser.FileFilter filter = new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".xlsx") || f.isDirectory();
            }

            public String getDescription() {
                return "Archivos Excel (*.xlsx)";
            }
        };

        fileChooser.setFileFilter(filter);
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            
            File sourceFile = new File("src/recursos/USD_COP Historical Data.xlsx");

            try {
                Files.copy(sourceFile.toPath(), fileToSave.toPath());
                JOptionPane.showMessageDialog(this, "Archivo descargado exitosamente.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al descargar el archivo: " + e.getMessage());
            }
        }
    
        

    }//GEN-LAST:event_jButton_verHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica_dolar_vs_pesoColombiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica_dolar_vs_pesoColombiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica_dolar_vs_pesoColombiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica_dolar_vs_pesoColombiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica_dolar_vs_pesoColombiano().setVisible(true);

            }
        });
    }

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_verHistorico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_WallPaper;
    private javax.swing.JLabel jLabel_grafica_dolar_vs_pesoColombiano;
    // End of variables declaration//GEN-END:variables
}
